{{- $name := printf "%s-cloudnative-pg-timescaledb" (include "dt4mob.fullname" .) }}
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: {{ $name }}
spec:
  images:
    - major: 15 # postgres major version
      image: timescale/timescaledb-ha:pg15-ts2.18-all